complementary_a: 0.98
ef_compensate_k: 0.182
emg_filter: true
er_compensate_k: 0.0
filter_order: 4
ha_compensate_k: 0.18
imu_filter: true
low_cutoff: 2
model_path: mann_s10_h2_f4
moving_ave: true
req_mode: false
send_fs: 20
send_save:
- arm_angle
- rpy
- gyroscope
- acceleration
- emg
sf_compensate_k: 0.1
socket_address: 127.0.0.1:5555
tcp_mode: false
window_size: 19
