complementary_a: 0.98
ha_compensate_k: 0.0
sf_compensate_k: 0.1
er_compensate_k: 0.0
ef_compensate_k: 0.182
emg_filter: true
filter_order: 4
imu_filter: true
low_cutoff: 2
moving_ave: true
req_mode: false
send_fs: 20
send_save:
- arm_angle
- rpy
- gyroscope
- acceleration
- emg
socket_address: 127.0.0.1:5555
tcp_mode: false
window_size: 19
model_path: 'mann_s10_h2_f4'
