complementary_a: 0.98
elbow_compensate_k: 0.182
emg_filter: true
filter_order: 4
imu_filter: true
low_cutoff: 2
model_path: multi2one_k
moving_ave: true
req_mode: false
send_fs: 20
send_save:
- arm_angle
- rpy
- gyroscope
- acceleration
- emg
socket_address: 127.0.0.1:5555
tcp_mode: false
window_size: 19
